# PNG2SVG Configuration File
# 数学配图智能转换系统配置

# Input/Output Settings
input_dir: "./pngs"
output_dir: "./out"

# Processing Settings
jobs: 4                         # 并行处理进程数
deskew: true                    # 自动纠偏
min_line_len: 25               # 最小线段长度（像素）
line_merge_angle_deg: 3        # 共线合并角度阈值（度）
line_merge_gap_px: 6           # 线段合并间隙阈值（像素）

# Model Settings
use_yolo_symbols: true          # 使用YOLO符号检测（若models/symbols_yolo.onnx不存在则自动=false）
yolo_symbols_weights: "models/symbols_yolo.onnx"
use_paddle_ocr: true           # 使用PaddleOCR（若不可用则退化为pytesseract）

# Advanced Processing
confidence_tta: true           # 旋转/镜像TTA测试时间增强
apply_constraint_solver: true  # 约束最小二乘"回正"

# SVG Output Settings
svg:
  scale: 1.0                   # SVG缩放比例
  stroke_main: 2               # 主线条宽度
  stroke_aux: 1                # 辅助线条宽度
  dash_pattern: "6,6"          # 虚线样式

# Export Settings
export:
  write_geojson: true          # 导出GeoJSON元数据
  write_svg: true              # 导出SVG文件

# Logging
log_level: "INFO"              # 日志级别: DEBUG, INFO, WARNING, ERROR

# Algorithm Parameters
algorithms:
  # Line Detection
  lsd:
    refine: true
    scale: 0.8
    sigma: 0.6
    quant: 2.0
    ang_th: 22.5
    log_eps: 0.0
    density_th: 0.7
    n_bins: 1024
  
  hough_lines:
    threshold: 50
    min_line_length: 25
    max_line_gap: 4
    
  # Circle Detection  
  hough_circles:
    dp: 1.2
    min_dist: 35      # Increased to avoid overlapping detections
    param1: 120       # Keep edge detection threshold
    param2: 50        # Increased accumulator threshold to reduce false positives
    min_radius: 15    # Increased minimum radius for mathematical diagrams
    max_radius: 0
    
  # Preprocessing
  preprocess:
    gaussian_blur_ksize: 3
    adaptive_thresh_blocksize: 35
    adaptive_thresh_c: 15
    
  # Constraint Solver
  constraints:
    max_iterations: 100
    tolerance: 1e-6
    huber_delta: 1.0
    lambda_parallel: 1.0
    lambda_perpendicular: 1.0
    lambda_collinear: 0.5
    lambda_equal_length: 0.8
    lambda_point_on_circle: 1.0
  
  # Dashed Line Detection
  dashed_line:
    min_dash_count: 1           # 最少虚线段数
    regularity_cv: 2.0          # 规律性变异系数阈值
    on_ratio_min: 0.05          # 最小ON比例 (lowered for line fragments)
    on_ratio_max: 0.85          # 最大ON比例 (increased to match observed patterns)
    min_gap_length: 1           # 最小间隙长度 (decreased to allow 1-pixel gaps)
    dash_gap_ratio_min: 0.01    # 虚线段与间隙比例最小值 (much lower for fragments)
    dash_gap_ratio_max: 10.0    # 虚线段与间隙比例最大值 (increased for varied patterns)
    
  # Arc Detection  
  arc_detection:
    min_contour_points: 5       # 轮廓最少点数
    min_contour_area: 50        # 轮廓最小面积
    coverage_threshold: 0.9     # 圆弧覆盖率阈值
    aspect_ratio_min: 0.6       # 最小长宽比（用于圆形度检查）